const initialState = () => [
    {
      id: "1",
      nombre: "Juan Bermudez",
      nota1: 5.4,
      nota2: 5.2,
      nota3: 5.1,
      nota4: 5,
      estado: "aprobado",
    },
    {
      id: "2",
      nombre: "Maria Buitrago",
      nota1: 5.4,
      nota2: 5.2,
      nota3: 5.1,
      nota4: 5,
      estado: "aprobado",
    },
    {
      id: "3",
      nombre: "Maria Buitrago",
      nota1: 5.4,
      nota2: 5.2,
      nota3: 5.1,
      nota4: 5,
      estado: "desaprobado",
    },
    {
      id: "4",
      nombre: "Mario Espineta",
      nota1: 5.4,
      nota2: 5.2,
      nota3: 5.1,
      nota4: 5,
      estado: "aprobado",
    },
    {
      id: "5",
      nombre: "Floyd Marcus",
      nota1: 5.4,
      nota2: 5.2,
      nota3: 5.1,
      nota4: 5,
      estado: "aprobado",
    },
    {
      id: "6",
      nombre: "Maria Martina",
      nota1: 5.4,
      nota2: 5.2,
      nota3: 5.1,
      nota4: 5,
      estado: "aprobado",
    },
    {
      id: "7",
      nombre: "Jeronimo Marcos",
      nota1: 5.4,
      nota2: 5.2,
      nota3: 5.1,
      nota4: 5,
      estado: "aprobado",
    },
    {
      id: "8",
      nombre: "Nico Nico",
      nota1: 5.4,
      nota2: 5.2,
      nota3: 5.1,
      nota4: 5,
      estado: "aprobado",
    },
    {
      id: "9",
      nombre: "Luma Lumana",
      nota1: 5.4,
      nota2: 5.2,
      nota3: 5.1,
      nota4: 5,
      estado: "aprobado",
    },
    {
      id: "10",
      nombre: "Kathe ui Designer",
      nota1: 5.4,
      nota2: 5.2,
      nota3: 5.1,
      nota4: 5,
      estado: "aprobado",
    },
  ];
  
  export default initialState;